### ISSUE TITLE
How to setup the configuration?

### ISSUE THREAD

**Issue by Samirbekaert** [jakubburkiewicz/uncss-brunch#1]
hi, thanks for this brunch plugin.

can't seem to get it running however. Disclaimer: I never used uncss before in any setting (grunt,...).

my site structure is as follows (including the built directory `public`):

```
root/  
|-app/
|--assets/   
|---index.html   
|---landing-01.html   
|--styles/
|---style.less
|-public/
|--index.html
|--landing-01.html
|--stylesheets/   
|---style.css
|-vendor/
|--styles/
|---bootstrap.css
|---icon-font.css
```

Assuming uncss-brunch runs solely on the command `brunch build -production`, how should I configure the plugin when:
*I use LESS
*my distribution directory is `/public` 
*my final compiled/built CSS file is located in `/public/stylesheets`
*my brunch setup concatenates css files from the `vendor/` folder with my main compiled style.less file

I'm trying this configuration, but it doesnt work.

```
plugins:
    uncss:
        options:
            csspath: 'stylesheets'
            htmlroot: 'public'
        files: ['index.html', 'landing-01.html']
```

perhaps I'm getting the mechanics of the plugin wrong?
